"""add_subtask_fields

Revision ID: 9a9d07be252c
Revises: b0e389d56bf2
Create Date: 2026-08-13 16:56:16.783118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9d07be252c'
down_revision: Union[str, Sequence[str], None] = 'b0e389d56bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('subtasks', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('subtasks', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('subtasks', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('subtasks', sa.Column(
        'assignees', sa.JSON(), nullable=False,
        server_default=sa.text("'[]'::json")
    ))
    op.add_column('subtasks', sa.Column(
        'status',
        sa.Enum('not_started', 'ongoing', 'completed', name='taskstatus'),
        nullable=False,
        server_default='not_started'
    ))
    op.add_column('subtasks', sa.Column(
        'updated_at', sa.DateTime(timezone=True),
        server_default=sa.text('now()'), nullable=False
    ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtasks', 'updated_at')
    op.drop_column('subtasks', 'status')
    op.drop_column('subtasks', 'assignees')
    op.drop_column('subtasks', 'due_date')
    op.drop_column('subtasks', 'start_date')
    op.drop_column('subtasks', 'remarks')
    # ### end Alembic commands ###
